name: Hama'ayan / <br> The Torah Spring
description: Hamaayan is prepared by laymen and published weekly for the edification and enjoyment of the reader who is lacking the time or ability to study the weekly parashah on his own. Hamaayan's goal is to acquaint the reader with a broad spectrum of traditional Torah commentary -- classical, recent and "obscure" -- as well as with aspects of Jewish history and thought.<br><br>Hamaayan is edited by Shlomo Katz. 
markdown: kramdown
permalink: /:heb_year/:title
alert: We are in the process of moving the Hama'ayan archives to a new site. Thank you for your patience.

url: http://thetorahspring.org

paginate: 10

file_loc: ../filestore/
link_loc: /assets/pdf/

analytics :
    provider : google
    google : 
        tracking_id : 'UA-53433541-1'

gems:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
